### ISSUE TITLE
Viennacl failed to build with cuda-11.0

### ISSUE THREAD

**Issue by beew** [viennacl/viennacl-dev#288]
Hi, Viennacl build failed with these message

```
 Building NVCC (Device) object examples/tutorial/CMakeFiles/matrix-free-cuda.dir/matrix-free-cuda_generated_matrix-free.cu.o
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations_col.hpp(1628): error: identifier "col_reduce_lcl_array" is undefined
          detected during:
            instantiation of "void viennacl::linalg::cuda::house_update_A_right_row_major_kernel(T *, T *, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with T=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations.hpp(2637): here
            instantiation of "void viennacl::linalg::cuda::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/matrix_operations.hpp(1034): here
            instantiation of "void viennacl::linalg::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(706): here
            instantiation of "__nv_bool viennacl::linalg::detail::householder_twoside(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vcl_size_t) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(722): here
            instantiation of "void viennacl::linalg::detail::tridiagonal_reduction(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(753): here
            instantiation of "void viennacl::linalg::detail::qr_method(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, __nv_bool) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(813): here
            instantiation of "void viennacl::linalg::qr_method_sym(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/examples/tutorial/qr_method.cu(111): here

/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations_col.hpp(1659): error: identifier "col_reduce_lcl_array" is undefined
          detected during:
            instantiation of "void viennacl::linalg::cuda::house_update_A_right_column_major_kernel(T *, T *, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with T=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations.hpp(2649): here
            instantiation of "void viennacl::linalg::cuda::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/matrix_operations.hpp(1034): here
            instantiation of "void viennacl::linalg::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(706): here
            instantiation of "__nv_bool viennacl::linalg::detail::householder_twoside(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vcl_size_t) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(722): here
            instantiation of "void viennacl::linalg::detail::tridiagonal_reduction(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(753): here
            instantiation of "void viennacl::linalg::detail::qr_method(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, __nv_bool) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(813): here
            instantiation of "void viennacl::linalg::qr_method_sym(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &) [with SCALARTYPE=float]" 
/home/bernard/src/ViennaCL-1.7.1/examples/tutorial/qr_method.cu(111): here

Scanning dependencies of target viennacl
[ 33%] Linking CXX shared library libviennacl.so
2 errors detected in the compilation of "/home/bernard/src/ViennaCL-1.7.1/examples/tutorial/qr_method.cu".
CMake Error at qr_method-cuda_generated_qr_method.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/bernard/src/ViennaCL-1.7.1/build/examples/tutorial/CMakeFiles/qr_method-cuda.dir//./qr_method-cuda_generated_qr_method.cu.o


make[2]: *** [examples/tutorial/CMakeFiles/qr_method-cuda.dir/build.make:65: examples/tutorial/CMakeFiles/qr_method-cuda.dir/qr_method-cuda_generated_qr_method.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2199: examples/tutorial/CMakeFiles/qr_method-cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Built target viennacl
```

cuda-11.0 on Ubuntu 20.04.
