### ISSUE TITLE
cuda-10.1 support

### ISSUE THREAD

**Issue by beew** [viennacl/viennacl-dev#273]
Viennacl 1.7.1 doesn't build for CUDA-10.1 (worked on CUDA-10.0)
OS is Ubuntu 16.04.6 
```Building CXX object examples/tutorial/CMakeFiles/custom-kernels.dir/custom-kernels.cpp.o
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations_col.hpp(1628): error: identifier "col_reduce_lcl_array" is undefined
          detected during:
            instantiation of "void viennacl::linalg::cuda::house_update_A_right_row_major_kernel(T *, T *, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with T=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations.hpp(2637): here
            instantiation of "void viennacl::linalg::cuda::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/matrix_operations.hpp(1034): here
            instantiation of "void viennacl::linalg::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(706): here
            instantiation of "__nv_bool viennacl::linalg::detail::householder_twoside(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vcl_size_t) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(722): here
            instantiation of "void viennacl::linalg::detail::tridiagonal_reduction(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(753): here
            instantiation of "void viennacl::linalg::detail::qr_method(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, __nv_bool) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(813): here
            instantiation of "void viennacl::linalg::qr_method_sym(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/examples/tutorial/qr_method.cu(111): here

/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations_col.hpp(1659): error: identifier "col_reduce_lcl_array" is undefined
          detected during:
            instantiation of "void viennacl::linalg::cuda::house_update_A_right_column_major_kernel(T *, T *, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) [with T=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/cuda/matrix_operations.hpp(2649): here
            instantiation of "void viennacl::linalg::cuda::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/matrix_operations.hpp(1034): here
            instantiation of "void viennacl::linalg::house_update_A_right(viennacl::matrix_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<NumericT, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with NumericT=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(706): here
            instantiation of "__nv_bool viennacl::linalg::detail::householder_twoside(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vector_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::vcl_size_t) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(722): here
            instantiation of "void viennacl::linalg::detail::tridiagonal_reduction(viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &, viennacl::matrix_base<SCALARTYPE, viennacl::vcl_size_t, viennacl::vcl_ptrdiff_t> &) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(753): here
            instantiation of "void viennacl::linalg::detail::qr_method(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &, __nv_bool) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/viennacl/linalg/qr-method.hpp(813): here
            instantiation of "void viennacl::linalg::qr_method_sym(viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, viennacl::matrix<SCALARTYPE, viennacl::row_major, 1U> &, std::vector<SCALARTYPE, std::allocator<SCALARTYPE>> &) [with SCALARTYPE=float]" 
/home/bernard/opt/cuda_test/ViennaCL-1.7.1/examples/tutorial/qr_method.cu(111): here

2 errors detected in the compilation of "/tmp/tmpxft_0000555e_00000000-6_qr_method.cpp1.ii".
CMake Error at qr_method-cuda_generated_qr_method.cu.o.cmake:266 (message):
  Error generating file
  /home/bernard/opt/cuda_test/ViennaCL-1.7.1/build/examples/tutorial/CMakeFiles/qr_method-cuda.dir//./qr_method-cuda_generated_qr_method.cu.o


examples/tutorial/CMakeFiles/qr_method-cuda.dir/build.make:63: recipe for target 'examples/tutorial/CMakeFiles/qr_method-cuda.dir/qr_method-cuda_generated_qr_method.cu.o' failed
make[2]: *** [examples/tutorial/CMakeFiles/qr_method-cuda.dir/qr_method-cuda_generated_qr_method.cu.o] Error 1
CMakeFiles/Makefile2:2138: recipe for target 'examples/tutorial/CMakeFiles/qr_method-cuda.dir/all' failed
make[1]: *** [examples/tutorial/CMakeFiles/qr_method-cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 19%] Building NVCC (Device) object libviennacl/CMakeFiles/viennacl.dir/src/viennacl_generated_blas2_opencl.cu.o
[ 19%] Linking CXX executable custom-kernels
[ 19%] Built target custom-kernels
[ 20%] Building NVCC (Device) object libviennacl/CMakeFiles/viennacl.dir/src/viennacl_generated_blas3.cu.o
Scanning dependencies of target qr-cuda
[ 21%] Linking CXX executable qr-cuda
[ 21%] Built target qr-cuda
[ 21%] Building NVCC (Device) object libviennacl/CMakeFiles/viennacl.dir/src/viennacl_generated_blas3_host.cu.o
[ 21%] Building NVCC (Device) object libviennacl/CMakeFiles/viennacl.dir/src/viennacl_generated_blas3_cuda.cu.o
[ 21%] Linking CXX executable amg
[ 21%] Built target amg
[ 21%] Linking CXX executable blas2
[ 21%] Built target blas2
Scanning dependencies of target viennacl
[ 21%] Linking CXX shared library libviennacl.so
[ 21%] Built target viennacl
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by karlrupp** [comment]
Thanks for bringing this up. I'll try to reproduce this on my local machine.

**Comment by karlrupp** [comment]
Thanks, @beew , this is now fixed.
